apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres-cluster
spec:
  instances: 1
  
  storage:
    storageClass: longhorn-postgres
    size: 10Gi

  postgresql:
    parameters:
      shared_preload_libraries: "vectors"
  imageName: "ghcr.io/tensorchord/cloudnative-pgvectors:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba"

  primaryUpdateStrategy: "unsupervised"

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgress-user-password
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-postgress-user-password

  monitoring:
    enablePodMonitor: true
