apiVersion: v1
kind: PersistentVolume
metadata:
  name: gittea-nfs
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.31.0.15
    path: /mnt/Main/kubernetes/Gittea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gittea-nfs
  namespace: gittea
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
#StorageClass created in Immich
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: manual
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "false"
#provisioner: kubernetes.io/manual
#reclaimPolicy: Retain # default value is Delete
#allowVolumeExpansion: true
#mountOptions:
#    - discard # this might enable UNMAP / TRIM at the block storage layer
#volumeBindingMode: Immediate
